### PR TITLE
feat: parse video from https://usdb.animux.de TXT files

### LINKED ISSUE #79: When adding a song YouTube ID should be enough
When I copy TXT from https://usdb.animux.de it already contains video data:

#ARTIST:Linkin Park
#TITLE:Valentine’s Day
#MP3:Linkin Park - Valentine’s Day.mp3
#CREATOR:SweetStar
#GENRE:None
#YEAR:2007
#LANGUAGE:English
#BPM:216.15
#GAP:3090
**#VIDEO:a=KAFOpywZbMM**,co=minutes-to-midnight-53a46caeae0d9.jpg,bg=linkin-park-4de523586c57e.jpg
: 0 3 9 My 
: 4 1 9 in
: 6 4 14 ~
: 12 6 12 side’s 
: 20 6 9 all 
: 28 4 7 turned 
: 36 2 9 to 
: 40 8 9 ash, 

It could be parsed from it if it's there or at least the input on the next step should also accept the ID and not only the full link.

### PR DESCRIPTION
**Pull request by waterplea**
Closes #79

### CODE REVIEW

**Comment by Asvarox** [comment]
The code looks good, do you think you could add a unit test to cover for the usdb's `#VIDEO`?

**Comment by waterplea** [comment]
> The code looks good, do you think you could add a unit test to cover for the usdb's `#VIDEO`?

I can try but after running `yarn` it seems like no everything gets properly installed, I get this error when I try to start or run tests:
```
Missing package: @rollup/rollup-win32-x64-msvc@npm:4.4.1
```
My node is `v20.9.0` and I'm using Windows 11. I have installed latest yarn with `npm i -g yarn`.

**Comment by Asvarox** [comment]
Oh, I see - the project was missing configuration to support Windows :) I've just merged the fix to `master`, if you rebase I think you'll be able to properly run the app locally

I tested your branch and noticed that when I copy the example input from #79 it currently produces an invalid link `https://www.youtube.com/watch?v==KAFOpywZbMM` (notice double `=`)

**Comment by waterplea** [comment]
Thank you. Got it fixed. Old test was failing for me but probably due to line break symbol on Windows. Updated the PR.

**Comment by Asvarox** [comment]
Thanks for the help, going to prod 🚀

**Pull request merged**
